prvard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prvard_main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prvard_main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_f, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_f, name='logout'),
    path('leave', views.leave, name='leave'),
    path('delete/<int:university_id>', views.delete, name='delete'),
    path('join', views.join, name='join'),
    path('Create_University', views.createu, name='createu'),
    path('Create/University/<str:Theme>', views.createu_f, name='createu_f'),
    path('mobile-blocked', views.mobile_blocked, name='mobile_blocked'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>', views.profile_other, name='profile_o'),
    path('members', views.members, name='members'),
    path('message', views.send_message, name='message'),
    path('inbox', views.inbox, name='inbox'),
    path('send', views.send, name='send'),
    path('message/<int:message_id>', views.show_message, name='show'),
    path('delete/message/<int:message_id>', views.delete_m, name='delete_m'),
    path('classes/', views.all_classes, name='all_classes'),
    path('entroll/<int:id>', views.Entroll, name='entroll'),
    path('Create/Class', views.createC, name='createC'),
    path('Delete/User/<int:id>', views.Delete_u, name='delete_u'),
    path('Login/<int:id>', views.Oclass, name='Oclass'),
    path('Class/<int:id>', views.Open_Class, name='Opclass'),
    path('Leave/Class/<int:id>', views.leaveC, name='Lclass'),
    path('Delete/Class/<int:id>', views.DeleteC, name='Dclass'),
    path('Member/Class/<int:id>', views.Cmember, name='Mclass'),
    path('Create/Week/<int:id>', views.Cweek, name='Cweek'),
    path('Edit/Week/<int:id>', views.Eweek, name='Eweek'),
    path('Show/Week/<int:id>', views.ShowW, name='ShowW'),
    path('Chat/Class/<int:id>', views.Chat1, name='Cclass'),
    path('Add/Message/Class/<int:id>', views.add_message, name='ACclass'),
    path('Delete/Lesson/<int:id>', views.Delete_L, name='DWclass'),


]

templates/harvard/all_classes.html
{% extends 'harvard/layout2.html' %}
{% block head %}{% endblock %}


{% block page_title %}
Classes
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}


<style>
    :root {
    --harvard-red: #A51C30;
    --harvard-black: #000000;
    --harvard-gray: #F5F5F5;
    --harvard-text: #333333;
    }
    @keyframes fadeIn {
        0%{
            transform: translateY(-10px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }
    @keyframes hr {
        0%{
            transform: translateY(30px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes hr-l {
        0%{
            scale: 1.1;
            opacity: 0;
        }
        100%{
            scale: 1;
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes pop {
        0%{
            scale: 1;
        }
        50%{
            scale: 1.1;
        }
        100%{
            scale: 1;
        }
    }
    @keyframes inX {
        0%{
            transform: translateX(-100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes inX-r {
        0%{
            transform: translateX(100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    .btn-f{
        text-decoration: none;
        max-width: 160px;
        padding: 15px 20px;
        background-color: #a51c30;
        color: white;
        border: none;
        border-radius: 20px;
        right: 0px;
        bottom: 5px;
        margin: 130px 15px 0 0 ;
        position: fixed;
        font-size: 1.2em;
        transition: 0.4s;
        animation: pop 0.7s;
    }
    .btn-f:hover{
        scale: 1.1;
    }
    form{
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        gap: 10px;

    }
    .search{
        height: 50px;
        width: 50%;
        margin-top: 20px;
        border: 1px solid black;
        border-radius: 32px;
        padding: 5px 20px;
        font-size: 1.4em;
    }
    .btn-search {
        background-color: black;
        color: white;
        height: 50px;
        padding: 5px 40px;
        border: 1px solid black;
        border-radius: 32px;
        margin-top: 20px;
        font-size: 1.1em;
        transition: 0.3s;

    }
    .btn-search:hover{
        background-color: #a51c30;
        color: rgb(255, 255, 255);
        scale: 1.009;
        
    }


    .cards{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
        margin-top: 40px;
    }

    .card{
        border: 1px solid rgb(32, 32, 32);
        width: 30%;

        border-radius: 32px;
        display: flex;
        flex-direction: column;

        align-items: center;
        margin-bottom: 10px;
        animation: inX 0.3s;

        
        transition: 0.3s;
        border: 1px solid rgb(0, 0, 0);
        box-shadow: 2px 3px 4px rgba(0, 0, 0, 0.233);
        background: linear-gradient(white, rgb(237, 237, 237));
    }
    .card:hover{
        border-left: 5px solid #a51c30;
        transform: translateY(-5px);
        
    }

    .card-title{
        font-size: 1.6em;
        font-family: Arial, Helvetica, sans-serif;
        margin: 10px;
        margin-top: 30px;
        margin-bottom: 20px;
    }
    .card-id{
        margin-bottom: 10px;
    }
    .card-btn{
        text-align: center;
        text-decoration: none;
        background-color: #a51c30;
        color: white;
        padding: 10px 0 10px 0;
        width: 100%;
        height: 20px;
        border-radius: 0 0 32px  32px;
        transition: 0.2s;
        background: linear-gradient(#a51c30, #72111f);
        
    }
    .card-btn:hover{
        background-color: rgb(83, 83, 83);
        background-color: #721120bb;
        opacity: 0.8;
    }
    .content{
        height: 100%;
    }
    .not{
        font-weight: 100;
        font-family: cursive;
        opacity: 0.6;
    }
    .card {
        border-radius: 4px;
        background: white;
        border: 1px solid #ddd;
        box-shadow: none;
        padding: 20px;
    }
    .card-btn {
        background: var(--harvard-red);
        border-radius: 4px;
    }

</style>

    <form action="{% url 'main:all_classes' %}" method="post">
        {% csrf_token %}
        <input autocomplete="off" autofocus type="search" name="q" placeholder="search by name" class="search">
        <input type="submit" value="search" class="btn-search"> 
    </form>

    <div class="body-t">
        <a class="btn-f" href="{% url 'main:createC' %}">Create your Class</a>
    </div>


        <div class="classes">
            <div class="cards">
                {% if classes %}
                    {% for class in classes %}
                        <div class="card">
                            <div class="card-title">{{ class.Name }}</div>
                            <div class="card-id">{{ class.id }}.0p</div>
                            <a href="{% url 'main:entroll' class.id %}" class="card-btn">Entroll</a>
                        </div>
                    {% endfor %}
                {% else %} 
                    <h2 class="not">There are no Classes here...</h2>
                {% endif %}
                

            </div>
        </div>


{% endblock body %}

templates/harvard/inbox.html
{% extends 'harvard/layout2.html' %}
{% block head %}{% endblock %}


{% block page_title %}
{{ title }}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}


<style>
    @keyframes fadeIn {
        0%{
            transform: translateY(-10px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }
    @keyframes hr {
        0%{
            transform: translateY(30px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes hr-l {
        0%{
            scale: 1.1;
            opacity: 0;
        }
        100%{
            scale: 1;
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes pop {
        0%{
            scale: 1;
        }
        50%{
            scale: 1.1;
        }
        100%{
            scale: 1;
        }
    }
    @keyframes inX {
        0%{
            transform: translateX(-100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes inX-r {
        0%{
            transform: translateX(100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    .btn-f{
        text-decoration: none;
        max-width: 160px;
        padding: 15px 20px;
        background-color: #a51c30;
        color: white;
        border: none;
        border-radius: 20px;
        right: 10px;
        top: 5px;
        margin: 130px 15px 0 0 ;
        position: fixed;
        font-size: 1.2em;
        transition: 0.4s;
    }
    .btn-f:hover{
        scale: 1.1;
    }
    .body-t{
        padding-top: 100px;
    }
    .messages{
        
        display: flex;
        flex-direction: column;
    }
    .message{
        padding: 5px 0;
        text-decoration: none;
        background-color: black;
        width: 100%;
        color: white;
        border: 1px solid white;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        height: 5.2em;
        transition: 0.2s;
        animation: hr-l 0.4s;
        border-radius: 7px;
        border-left: 6px solid #a51c30;
        
        
    }
    .message:hover{
        background-color: rgb(53, 53, 53);
    }
    .info{
        font-size: 1em;
        margin-left: 10px;

    }
    .Title-d{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .Title{
        font-size: 1.7em;
        font-family:Verdana, Geneva, Tahoma, sans-serif;
    }
    .opened {
    background-color: #1c1c1c;
    background-color: #000000cd;  /* Read: black */
    color: #e3e3e3c7;             /* Dim text */
    }

    .unopened {
    background-color: #1c1c1c;
    background-color: #000000cd; 
    font-weight: bold;       /* Bold text */
    border-left: 4px solid #0077ff;  /* Blue bar */
    }

    .dot {
        display: inline-block;
        width: 8px;
        height: 8px;
        background: #0077ff;
        border-radius: 50%;
        margin-left: 10px;
    }

    a.message {
    display: block;
    color: white; /* لون النص الطبيعي */
    text-decoration: none;
    }

    a.message.opened {

    background-color: black;
    background-color: #1c1c1c;
    }

    a.message.unopened {
    background-color: rgb(53, 53, 53);
    }

    a.message:hover {
    background-color: #444;
    color: rgb(255, 255, 255);
    }


</style>
    <div class="body-t">

        <a class="btn-f" href="{% url 'main:message'  %}">Send a message</a>

        <div class="messages">
            {% for message in messages %}
            {% if message.active %}
                <a class="message {% if message.opened %}opened{% else %}unopened{% endif %}" href="{% url 'main:show' message.id %}" >
                    <div class="mail info">
                        {% if title == "Inbox" %}
                            {{ message.From }}
                        {% else %}
                            {{ message.To }}
                        {% endif %}
                            {% if not message.opened %}
                                <span class="dot"></span>
                            {% endif %}
                    </div>
                    <div class="Title-d">
                        <div class="Title">{{ message.Title }}</div>
                    </div>
                    <div class="date info">{{message.DateTime.date}}</div>
                </a>
            {% endif %}
            {% endfor %}
            </div>
    </div>



{% endblock body %}

templates/harvard/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Harvard</title>
    <link rel="stylesheet" href="{% static 'harvard/css/index.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
</head>
<body>
    
    <div class="head">
        <p class="h-p">
            This Website is created by Prroer. <br>
            Prvard is full educational platform that's like a university, you choose harvard theme. <br>
            If you need help please send email to prvard@gmail.com
        </p>
        <div class="h-d-btn">
            <a class="h-btn" href="#">
                More informations
            </a>
        </div>
    </div>

    <div class="content">
        <div class="c-header">
            <div class="c-r">
                <a href="{% url 'main:index' %}"><img src="{% static 'harvard/img/harvard.png' %}" alt="Harvard" width="120px"></a>
            </div>
            <div class="c-l">
                <p class="c-p">{{ university.Prvard_id }}</p>
                <div class="profile">
                    <img src="{{ student.Photo.url }}" alt="Harvard" width="50px" class="T">
                      <div class="profile-menu">
                            <a href="{% url 'main:profile' %}">Profile</a>
                            <a href="{% url 'main:leave' %}">Leave</a>
                            {% if is_admin %}
                                <a href="{% url 'main:delete' university.id %}">Deleat</a>
                            {% endif %}
                            <a href="{% url 'main:logout' %}">Logout</a>
                        </div>
                </div>
            </div>
        </div>
        <div class="c-body">
            Welcome To Harvard
        </div>
    </div>
    <main>
        <div class="slide">
            <div class="navs">
                <a href="{% url 'main:inbox' %}">Inbox</a>
                <a href="{% url 'main:send' %}">Send</a>
                <a href="{% url 'main:message' %}">Message</a>
                <a href="{% url 'main:members' %}">Members</a>
            </div>
        </div>
        <div class="classes">
            <a href="{% url 'main:all_classes' %}" class="classe-btn">Entroll more</a>
            <h1 class="m-title">Your Classes</h1>
            <div class="cards">
                {% if classes %}
                    {% for class in classes %}
                        <div class="card">
                            <div class="card-title">{{ class.Name }}</div>
                            <div class="card-id">{{ class.id }}.0p</div>
                            <a href="{% url 'main:Oclass' class.id %}" class="card-btn">Continue</a>
                        </div>
                    {% endfor %}
                {% else %} 
                    <h2 class="not">There are no Classes yet...</h2>
                {% endif %}
                

            </div>

        </div>

    </main>


<script>
    const profile = document.querySelector('.profile');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>

</body>
</html>

templates/harvard/layout1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Harvard</title>
    <link rel="stylesheet" href="{% static 'harvard/css/layout1.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <div class="head">
        <a href="{% url 'main:index' %}" class="c-r"><img src="{% static 'harvard/img/harvard.png' %}" alt="Harvard" width="120px"></a>
        <div class="title">{% block page_title %}{% endblock %}</div>
        <div class="c-l">
            <p class="id">{% block id %}{% endblock %}</p>
            <div class="profile">
                <img src="{% block img %}{% endblock %}" alt="Harvard" width="50px" class="T">
                    <div class="profile-menu">
                        <a href="{% url 'main:profile' %}">Profile</a>
                        <a href="{% url 'main:leave' %}">Leave</a>
                        {% if is_admin %}
                            <a href="{% url 'main:delete' university.id %}">Deleat</a>
                        {% endif %}
                        <a href="{% url 'main:logout' %}">Logout</a>
                    </div>
            </div>
        </div>
    </div>
    <div class="content">
        {% block body %}{% endblock %}
    </div>

<script>
    const profile = document.querySelector('.profile');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/harvard/layout2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Harvard</title>
    <link rel="stylesheet" href="{% static 'harvard/css/layout2.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <div class="head">
        <a href="{% url 'main:index' %}" class="c-r"><img src="{% static 'harvard/img/harvard.png' %}" alt="Harvard" width="120px"></a>
        <div class="title">{% block page_title %}{% endblock %}</div>
        <div class="c-l">
            <p class="id">{% block id %}{% endblock %}</p>
            <div class="profile">
                <img src="{% block img %}{% endblock %}" alt="Harvard" width="50px" class="T">
                    <div class="profile-menu">
                        <a href="{% url 'main:profile' %}">Profile</a>
                        <a href="{% url 'main:leave' %}">Leave</a>
                        {% if is_admin %}
                            <a href="{% url 'main:delete' university.id %}">Deleat</a>
                        {% endif %}
                        <a href="{% url 'main:logout' %}">Logout</a>
                    </div>
            </div>
        </div>
    </div>
    <div class="content">
        {% block body %}{% endblock %}
    </div>

<script>
    const profile = document.querySelector('.profile');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/harvard/members.html
{% extends 'harvard/layout2.html' %}
{% block head %}{% endblock %}


{% block page_title %}
Members
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}
<style>
    form{
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        gap: 10px;

    }
    .search{
        height: 50px;
        width: 50%;
        margin-top: 20px;
        border: 1px solid black;
        border-radius: 32px;
        padding: 5px 20px;
        font-size: 1.4em;
    }
    .btn-search {
        background-color: black;
        color: white;
        height: 50px;
        padding: 5px 40px;
        border: 1px solid black;
        border-radius: 32px;
        margin-top: 20px;
        font-size: 1.1em;
        transition: 0.3s;

    }
    .btn-search:hover{
        background-color: #a51c30;
        color: rgb(255, 255, 255);
        scale: 1.009;
        
    }
    .cards{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        gap: 30px;
        margin-top: 30px;
    }
    .card{
        width: 20%;
        hight: 150px;
        background-color: rgb(36, 36, 36);
        color: white;
        padding: 10px 0px 0px 0px ;
        transition: 0.3s;
    }
    .card:hover{
        transform: translateY(-10px);
    }
    .top{
        display: flex;

    }
    .t-left{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items:flex-start;
    }
    .img {
        width: 70px;     
        height: 70px;     
        border-radius: 10px; 
        overflow: hidden;  

        border: 1px solid rgb(0, 0, 0);
        border-image-outset: 50px;
        margin: 10px;
    }


    .img > img {
        width: 100%;
        height: 100%;
        border-radius: 10px;
        object-fit: cover;
        animation: fadeIn 0.3s;
    }
    .btn_see{
        text-decoration: none;
        color: rgb(0, 0, 0);
        background-color: white;
        width: 100%;
        border: none;
        border-radius: 0px 0px 32px 32px;
        margin-bottom: 0;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px ;
        transition: 0.3s;
        background-color: #a51c30;
        color: rgb(255, 255, 255);

    }
    .btn_see:hover{
        background-color: #a51c31aa;
        color: rgb(255, 255, 255);
        scale: 1.009;
        
    }

</style>



<form action="{% url 'main:members' %}" method="post">
    {% csrf_token %}
    <input autocomplete="off" autofocus type="search" name="q" placeholder="search by name" class="search">
    <input type="submit" value="search" class="btn-search"> 
</form>




<div class="cards">
    {% for student in students %}
        <div class="card">
            <div class="top">
                <a class="img" href="{{student.Photo.url}}"><img src="{{student.Photo.url}}" alt="{{student.Name}}" width="50px"></a>
                
                <div class="t-left">
                    <div class="name">
                        {{student.Name}}
                    </div>
                    <div class="points">{{student.Points}} Points</div>
                </div>
            </div>
            <div class="mail">
                {{ student.Mail_1 }}
            </div>
            <a class="btn_see" href="{% url 'main:profile_o' student.Id %}">
                See more
            </a>
        </div>
    {% endfor %}
</div>

 


{% endblock %}

templates/harvard/profile.html
{% extends 'harvard/layout1.html' %}
{% block page_title %}{{request.user.first_name}}{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ user_st.Photo.url }}{% endblock %}
{% block body %}
<style>
    :root {
    --harvard-red: #A51C30;
    --harvard-black: #000000;
    --harvard-gray: #F5F5F5;
    --harvard-text: #333333;
    }
    @keyframes fadeIn {
        0%{
            transform: translateY(-10px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes pop {
        0%{
            scale: 1;
        }
        50%{
            scale: 1.1;
        }
        100%{
            scale: 1;
        }
    }
    @keyframes inX {
        0%{
            transform: translateX(-100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    .info{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
    }
    .photo{
        width: 300px;
        height: 300px;
        border-radius: 10px;
        overflow: hidden;
        border: 1px solid rgb(255, 255, 255);
        border-image-outset: 50px;
        margin-top: 60px;
        margin-bottom: 20px;
        animation: fadeIn 0.3s;
    }
    .photo > img{
        width: 100%;
        height: 100%;
        object-fit: cover;
        
        
    }
    .name{
        text-align: center;
        color: white;
        font-size: 3em;
        font-weight: 700;
        width: 100%;
        font-family:initial;
        animation: hr-l 0.5s;
    }
    .mail{
        text-align: center;
        color: white;
        font-size: 2em;
        width: 100%;
        font-family:sans-serif;
        animation: hr-l 0.5s;

    }
    .points{
        margin: 20px;
        background: linear-gradient(yellow, rgb(255, 183, 0));
        padding: 10px 80px ;
        border-radius: 32px;
        font-weight: 800;
        color: rgb(0, 0, 0);
        margin-bottom: 50px;
        animation: pop 0.5s;
    }
    .cards{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
        width: 100%;
        margin-bottom: 30px;
    }


    .card{
        background-color: white;
        width: 20%;

        border-radius: 32px;
        display: flex;
        flex-direction: column;

        align-items: center;
        margin-bottom: 10px;
        animation: inX 0.3s;
    }

    .card-title{
        font-size: 1.6em;
        margin: 10px;
        margin-top: 30px;
        margin-bottom: 20px;
    }
    .card-id{
        margin-bottom: 10px;
    }
    .card-btn{
        text-align: center;
        text-decoration: none;
        background-color: black;
        color: white;
        padding: 10px 0 10px 0;
        width: 100%;
        height: 20px;
        border-radius: 0 0 32px  32px;
        transition: 0.2s;
        
    }
    .card-btn:hover{
        background-color: rgb(83, 83, 83);
    }
    .btn-f{
        text-decoration: none;
        max-width: 160px;
        padding: 15px 20px;
        background-color: #a51c30;
        color: white;
        border: none;
        border-radius: 20px;
        right: 10px;
        top: 5px;
        margin: 130px 15px 0 0 ;
        position: fixed;
        font-size: 1.2em;
        transition: 0.4s;
    }
    .btn-f:hover{
        scale: 1.1;
    }
    .Title{
        margin-bottom: 60px;
        color: white;
    }

    .cards{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
    }

    .card{
        border: 1px solid rgb(32, 32, 32);
        width: 30%;

        border-radius: 32px;
        display: flex;
        flex-direction: column;

        align-items: center;
        margin-bottom: 10px;
        animation: inX 0.3s;

        
        transition: 0.3s;
        border: 1px solid rgb(0, 0, 0);
        box-shadow: 2px 3px 4px rgba(0, 0, 0, 0.233);
        background: linear-gradient(white, rgb(237, 237, 237));
    }
    .card:hover{
        border-left: 5px solid #a51c30;
        transform: translateY(-5px);
        
    }

    .card-title{
        font-size: 1.6em;
        margin: 10px;
        margin-top: 30px;
        margin-bottom: 20px;
    }
    .card-id{
        margin-bottom: 10px;
    }
    .card-btn{
        text-align: center;
        text-decoration: none;
        background-color: #a51c30;
        color: white;
        padding: 10px 0 10px 0;
        width: 100%;
        height: 20px;
        border-radius: 0 0 32px  32px;
        transition: 0.2s;
        background: linear-gradient(#a51c30, #72111f);
        
    }
    .card-btn:hover{
        background-color: rgb(83, 83, 83);
        background-color: #721120bb;
        opacity: 0.8;
        
    }

    .card {
    border-radius: 4px;
    background: white;
    border: 1px solid #ddd;
    box-shadow: none;
    padding: 20px;
    }
    .card-btn {
    background: var(--harvard-red);
    border-radius: 4px;
    }
    .not{
        font-weight: 100;
        font-family: cursive;
        opacity: 0.6;
        color: white;
    }
</style>
{% if is_Admin %}
    {% if other %}
        <a class="btn-f" href="{% url 'main:delete_u' user.id %}">Delete</a>
    {% endif %}
{% endif %}
<div class="info">
    <div class="photo">
        <img src="{{ student.Photo.url }}" alt="Harvard" width="300px" class="">
    </div>
    <div class="name">{{user.first_name}}</div>
    <div class="mail">{{user.email}}</div>
    <div class="points">{{student.Points}} Points</div>
    <h1 class="Title title">Classes</h1>
    <div class="cards">
        {% if classes %}
            {% for class in classes %}
                <div class="card">
                    <div class="card-title">{{ class.Name }}</div>
                    <div class="card-id">{{ class.id }}.0p</div>
                    {% if other %}
                        <a href="{% url 'main:entroll' class.id %}" class="card-btn">Entroll</a>
                    {% else %}
                        <a href=" {% url 'main:Oclass' class.id %}" class="card-btn">Continue</a>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %} 
            <h2 class="not">no Classes yet...</h2>
        {% endif %}
    </div>
    
</div>


{% endblock %}