prvard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prvard_main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prvard_main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_f, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_f, name='logout'),
    path('leave', views.leave, name='leave'),
    path('delete/<int:university_id>', views.delete, name='delete'),
    path('join', views.join, name='join'),
    path('Create_University', views.createu, name='createu'),
    path('Create/University/<str:Theme>', views.createu_f, name='createu_f'),
    path('mobile-blocked', views.mobile_blocked, name='mobile_blocked'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>', views.profile_other, name='profile_o'),
    path('members', views.members, name='members'),
    path('message', views.send_message, name='message'),
    path('inbox', views.inbox, name='inbox'),
    path('send', views.send, name='send'),
    path('message/<int:message_id>', views.show_message, name='show'),
    path('delete/message/<int:message_id>', views.delete_m, name='delete_m'),
    path('classes/', views.all_classes, name='all_classes'),
    path('entroll/<int:id>', views.Entroll, name='entroll'),
    path('Create/Class', views.createC, name='createC'),
    path('Delete/User/<int:id>', views.Delete_u, name='delete_u'),
    path('Login/<int:id>', views.Oclass, name='Oclass'),
    path('Class/<int:id>', views.Open_Class, name='Opclass'),
    path('Leave/Class/<int:id>', views.leaveC, name='Lclass'),
    path('Delete/Class/<int:id>', views.DeleteC, name='Dclass'),
    path('Member/Class/<int:id>', views.Cmember, name='Mclass'),
    path('Create/Week/<int:id>', views.Cweek, name='Cweek'),
    path('Edit/Week/<int:id>', views.Eweek, name='Eweek'),
    path('Show/Week/<int:id>', views.ShowW, name='ShowW'),
    path('Chat/Class/<int:id>', views.Chat1, name='Cclass'),
    path('Add/Message/Class/<int:id>', views.add_message, name='ACclass'),
    path('Delete/Lesson/<int:id>', views.Delete_L, name='DWclass'),


]

templates/class/Cmember.html
{% extends 'class/layout4.html' %}
{% block head %}{% endblock %}


{% block page_title %}
{{class.Name}}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}


<style>
    form{
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        gap: 10px;

    }
    .search{
        height: 50px;
        width: 50%;
        margin-top: 20px;
        border: 1px solid black;
        border-radius: 32px;
        padding: 5px 20px;
        font-size: 1.4em;
    }
    .btn-search {
        background-color: black;
        color: white;
        height: 50px;
        padding: 5px 40px;
        border: 1px solid black;
        border-radius: 32px;
        margin-top: 20px;
        font-size: 1.1em;
        transition: 0.3s;

    }
    .btn-search:hover{
        background-color: #a51c30;
        color: rgb(255, 255, 255);
        scale: 1.009;
        
    }
    .cards{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        gap: 30px;
        margin-top: 30px;
    }
    .card{
        width: 30%;
        hight: 150px;
        background-color: rgb(36, 36, 36);
        color: white;
        padding: 10px 0px 0px 0px ;
        transition: 0.3s;
    }
    .card:hover{
        transform: translateY(-10px);
    }
    .top{
        display: flex;

    }
    .t-left{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items:flex-start;
    }
    .img {
        width: 70px;     
        height: 70px;     
        border-radius: 10px; 
        overflow: hidden;  

        border: 1px solid rgb(0, 0, 0);
        border-image-outset: 50px;
        margin: 10px;
    }


    .img > img {
        width: 100%;
        height: 100%;
        border-radius: 10px;
        object-fit: cover;
        animation: fadeIn 0.3s;
    }
    .btn_see{
        text-decoration: none;
        color: rgb(0, 0, 0);
        background-color: white;
        width: 100%;
        border: none;
        border-radius: 0px 0px 32px 32px;
        margin-bottom: 0;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px ;
        transition: 0.3s;
        background-color: #a51c30;
        color: rgb(255, 255, 255);

    }
    .btn_see:hover{
        background-color: #a51c31aa;
        color: rgb(255, 255, 255);
        scale: 1.009;
        
    }

</style>

<form action="{% url 'main:Mclass' class.id %}" method="post">
    {% csrf_token %}
    <input autocomplete="off" autofocus type="search" name="q" placeholder="search by name" class="search">
    <input type="submit" value="search" class="btn-search"> 
</form>




<div class="cards">
    {% for student in students %}
        <div class="card">
            <div class="top">
                <a class="img" href="{{student.Photo.url}}"><img src="{{student.Photo.url}}" alt="{{student.Name}}" width="50px"></a>
                
                <div class="t-left">
                    <div class="name">
                        {{student.Name}}
                    </div>
                    <div class="points">{{student.Points}} Points</div>
                </div>
            </div>
            <div class="mail">
                {{ student.Mail_1 }}
            </div>
            <a class="btn_see" href="{% url 'main:profile_o' student.Id %}">
                See more
            </a>
        </div>
    {% endfor %}
</div>



 


{% endblock %}

templates/class/createW.html
{% extends 'harvard/layout2.html' %}
{% block head %}{% endblock %}


{% block page_title %}
Create {{type}}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}
<style>
    .all{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }
    form{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: white;
        margin-top: 50px;
        padding: 20px 20px;
        gap: 10px;
        border: 1px solid black;
        border-radius: 20px;
        width: 50%;
    }
    .ii{
        width: 60%;
        display: flex;
        flex-direction: column;
        justify-content: center;

        gap: 10px;
       
    }
    .input{
        width: 100%;
        height: 30px;
        font-size: 1.3em;
        margin-bottom: 5px;
        border: 1px solid black;
        border-radius: 20px;
        padding: 5px 10px ;
    }
    .T{
        font-size: 1.4em;
        font-weight: 500;
        text-align: center;
    }
    .select{
        margin-bottom: 40px;
        font-weight: 400;
        min-height: 40px;
        width: 100%;
    }
    .btn-s{
        background-color: #a51c30;
        color: white;
        width: 100%;
        min-height: 40px;
        border-radius: 10px;
        font-size: 1em;
        transition: 0.3s;
    }
    .btn-s:hover{
        background-color: #91192b;
        scale: 1.01;
    }
    .mark{
        height: 150px;
        font-size: 1em;
        
    }
</style>

<div class="all">
    <form action="" method="post">
        <h1 class="T">Add {{type}}</h1>
        {% csrf_token %}
        <div class="ii">
            <div class="label">Title</div>
            <input type="text" name="title" class="input name" placeholder="Title:">
            <input type="hidden" name="id" value="{{class.id}}">
        </div>

        <div class="ii">
        <div class="label labelm">Markdown</div>
        <textarea name="mark" id="" class="input mark"></textarea>
        </div>
        <input type="submit" value="Next" class="btn-s">
    </form>
</div>


{% endblock %}

templates/class/editW.html
{% extends 'harvard/layout2.html' %}
{% block head %}{% endblock %}


{% block page_title %}
Edit {{type}}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}
<style>
    .all{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }
    form{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: white;
        margin-top: 50px;
        padding: 20px 20px;
        gap: 10px;
        border: 1px solid black;
        border-radius: 20px;
        width: 50%;
    }
    .ii{
        width: 60%;
        display: flex;
        flex-direction: column;
        justify-content: center;

        gap: 10px;
       
    }
    .input{
        width: 100%;
        height: 30px;
        font-size: 1.3em;
        margin-bottom: 5px;
        border: 1px solid black;
        border-radius: 20px;
        padding: 5px 10px ;
    }
    .T{
        font-size: 1.4em;
        font-weight: 500;
        text-align: center;
    }
    .select{
        margin-bottom: 40px;
        font-weight: 400;
        min-height: 40px;
        width: 100%;
    }
    .btn-s{
        background-color: #a51c30;
        color: white;
        width: 100%;
        min-height: 40px;
        border-radius: 10px;
        font-size: 1em;
        transition: 0.3s;
    }
    .btn-s:hover{
        background-color: #91192b;
        scale: 1.01;
    }
    .mark{
        height: 150px;
        font-size: 1em;
        
    }
</style>

<div class="all">
    <form action="" method="post">
        <h1 class="T">Edit {{type}}</h1>
        {% csrf_token %}
        <div class="ii">
            <div class="label">Title</div>
            <input type="text" name="title" class="input name" placeholder="Title:" value="{{title}}">
            <input type="hidden" name="id" value="{{class.id}}">
        </div>

        <div class="ii">
        <div class="label labelm">Markdown</div>
        <textarea name="mark" id="" class="input mark">{{mark}}</textarea>
        </div>
        <input type="submit" value="Next" class="btn-s">
    </form>
</div>


{% endblock %}

templates/class/layout4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Harvard</title>
    <link rel="stylesheet" href="{% static 'harvard/css/layout4.css' %}">
    <link rel="stylesheet" href="{% static 'harvard/css/layout4.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <div class="head">
        <a href="{% url 'main:index' %}" class="c-r"><img src="{% static 'harvard/img/harvard.png' %}" alt="Harvard" width="120px"></a>
        <div class="title">{% block page_title %}{% endblock %}</div>
        <div class="c-l">
            <p class="id">{% block id %}{% endblock %}</p>
            <div class="profile">
                <img src="{% block img %}{% endblock %}" alt="Harvard" width="50px" class="T">
                    <div class="profile-menu">
                        <a href="{% url 'main:profile' %}">Profile</a>
                        <a href="{% url 'main:Lclass' class.id %}">Leave Class</a>
                        {% if is_admin %}
                            <a href="{% url 'main:Dclass' class.id %}">Deleat Class</a>
                        {% endif %}
                        {% if is_admin %}
                            {% if lessoni %}
                                <a href="{% url 'main:Eweek' lesson_id %}">Edit {{type}}</a>
                            {% endif %}
                        {% endif %}
                        <a href="{% url 'main:logout' %}">Logout</a>
                    </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="slide">
            <a href="{% url 'main:Opclass' class.id %}" class="{% if is_t == '1' %}in_t{% endif %}">Class</a>
            <a href="{% url 'main:Mclass' class.id %}" class="{% if is_t == '2'%}in_t{% endif %}">Members</a>
            <a href="{% url 'main:Cclass' class.id %}" class="{% if is_t == '3'%}in_t{% endif %}">Chat</a>
            <a href="https://cs50.dev" class="{% if is_t == '4'%}in_t{% endif %}">Code Space</a>
            <a href="https://github.com" class="{% if is_t == '5'%}in_t{% endif %}">Github</a>
        </div>
        <div class="body">{% block body %}{% endblock %}</div>
    </div>

<script>
    const profile = document.querySelector('.profile');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/class/login.html
{% extends 'harvard/layout3.html' %}
{% load static %}
{% block head %}{% endblock %}


{% block page_title %}
Create Class
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}
<style>
    .all{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }
    form{
        width: 30%;
        display: flex;
        flex-direction: column;
        background-color: white;
        margin-top: 8px;
        border: none;
        border-radius: 10px;
        padding-bottom: 20px;
    }
    .ii{
        width: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;

        gap: 10px;
       
    }
    .input{
        width: 83%;
        height: 30px;
        font-size: 1em;
        font-weight: 100;
        margin-bottom: 5px;
        border: 1px solid rgb(118, 118, 118);
        border-radius: 5px;
        padding: 5px 10px ;

        
    }
    .T{
        width: 100%;
        align-items: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding-bottom: 20px;
        border-bottom: 1px solid rgba(118, 118, 118, 0.311);
    }
    .T > img{
        width: 215px;

    }
    .select{
        margin-bottom: 40px;
        font-weight: 400;
        min-height: 40px;
        width: 100%;
    }
    .btn-s{
        background-color: rgb(118, 118, 118);
        color: white;

        min-height: 40px;
        border: none;
        border-radius: 10px;
        font-size: 1em;
        transition: 0.3s;
        margin-right: 40px;
        margin-top: 10px;
        margin-bottom: 20px;
    }
    .btn-s:hover{
        background-color: rgb(86, 86, 86);
    }

    .iii{
        padding-left: 40px;
        padding-bottom: 30px;

    }
    .iii > h1{
        font-size: 1.5em;
        font-family: 'Segoe UI', Tahoma, Verdana, sans-serif;
        font-weight: 200;
        margin-bottom: 30px;
       
        
    }
    .end{
        text-decoration: none;
        color: rgb(118, 118, 118);
        margin-top: 20px;
    }
    .end:hover{
        text-decoration:underline;
    }
    .Error{
        color: rgb(119, 0, 0);
    }
    .label{
        font-weight: 300;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
</style>


<!-- <form action="{% url 'main:login' %}" method="post">
    {% csrf_token %}
    <div class="sign">Sign In</div>
    <div class="message">{{message}}</div>
    <div class="label">Username</div>
    <input type="text" name="username" class="input">
    <div class="label">Password</div>
    <input type="password" name="password" class="input">
    <input type="submit" value="Sign In" class="btn">
    <a class="other" href="{% url 'main:register' %}">Register?</a>
            </form> -->
<div class="all">
    <form action="{% url 'main:Oclass' id %}" method="post">
        <h1 class="T"><img src="{% static 'harvard/img/key.png' %}" alt="Harvard Key" width="200px"></h1>
        {% csrf_token %}
        
        <div class="iii">
            <h1>Sign In</h1>
            
            <div class="ii">
                <div class="label">Username</div>
                <input type="text" name="username" class="input name" >
            </div>
<!-- 
            <div class="ii">
                <div class="label">Password</div>
                <input type="password" name="password" class="input">
            </div> -->
            <div class="Error">{{ message }}</div>
            <div class="ii"><input type="submit" value="Next" class="btn-s"></div>

            <a class="end" href="https://key.harvard.edu/account-recovery/request-login-name-reminder">Forgot Username?</a>

        </div>
        
        
    </form>
</div>


{% endblock %}

templates/class/main.html
{% extends 'class/layout4.html' %}
{% block head %}{% endblock %}


{% block page_title %}
{{class.Name}}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}


<style>
    .lessons{
        width: 100%;
    }
    .lesson{
        padding: 5px 0;
        text-decoration: none;
        background-color: black;
        width: 100%;
        color: white;
        border: 1px solid white;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        height: 5.2em;
        transition: 0.2s;
        animation: hr-l 0.4s;
        border-radius: 7px;
        border-left: 6px solid #a51c30;
        text-align: center;
        display: flex;
        justify-content: center;
        align-items: center;
        border-left: 6px solid #a51c30;
        margin-left: 0vh;
        font-size: 1em;
        font-weight: 500;
        cursor: pointer;
    }
    .lesson:hover{
        background-color: rgb(53, 53, 53);
    }

    .btn-f{
        text-decoration: none;
        max-width: 160px;
        padding: 15px 20px;
        background-color: #a51c30;
        color: white;
        border: none;
        border-radius: 20px;
        right: 10px;
        top: 5px;
        margin: 130px 15px 0 0 ;
        position: fixed;
        font-size: 1em;
        transition: 0.4s;
        cursor: pointer;
        z-index: 997;
    }
    .btn-f:hover{
        scale: 1.1;
    }
    .not{
        text-align: center;
        font-weight: 100;
        font-family: cursive;
        opacity: 0.6;
    }

</style>
{% if is_admin %}
    <a class="btn-f" href="{% url 'main:Cweek' class.id %}">Add new {{type}}</a>
{% endif %}

{% if lessons %}
        <div class="lessons">
            {% for lesson in lessons %}
                <a class="lesson" href="{% url 'main:ShowW' lesson.id %}"><h1>{{type}} {{lesson.Number}}</h1></a>
            {% endfor %}
        </div>
{% else %} 
    <h2 class="not">There are no {{ type }} yet...</h2>
{% endif %}



 


{% endblock %}

templates/class/showW.html
{% extends 'class/layout4.html' %}
{% block head %}{% endblock %}


{% block page_title %}
{{class.Name}}
{% endblock %}
{% block id %}{{ university.Prvard_id }}{% endblock %}
{% block img %}{{ student.Photo.url }}{% endblock %}
{% block body %}


<style>
    @keyframes fadeIn {
        0%{
            transform: translateY(-10px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }
    @keyframes hr {
        0%{
            transform: translateY(30px);
            opacity: 0;
        }
        100%{
            transform: translateY(0);
            opacity: 1;
        }
    }

    @keyframes pop {
        0%{
            scale: 1;
        }
        50%{
            scale: 1.1;
        }
        100%{
            scale: 1;
        }
    }
    @keyframes inX {
        0%{
            transform: translateX(-100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes inX-r {
        0%{
            transform: translateX(100%);
            opacity: 0;
        }
        100%{
            transform: translateX(0);
            opacity: 1;
        }
    }
    .delete{
        background-color: brown;
        text-decoration: none;
        color: white;
        padding: 10px 50px;
        border: 1px solid black;
        border-radius: 32px;
        position: fixed;
        bottom: 10px;
        right: 10px;
        transition: 0.3s;
        animation: pop 0.3s;
    }
    .delete:hover{
        scale: 1.1;
    }
    .date{
        background-color: rgb(0, 0, 0);
        text-decoration: none;
        color: white;
        padding: 10px 50px;
        border: 1px solid black;
        border-radius: 32px;
        position: fixed;
        bottom: 10px;
        left: 10px;
        transition: 0.3s;
        animation: inX 0.3s;
    }
body {
    font-family: Georgia, 'Times New Roman', serif;
    background: #999999;
    color: #eee;
    margin: 0;
    padding: 0;
}

    .main {
        padding-top: 60px;
    }

    .Title-d {
        padding: 20px 40px;
        background-color: #1c1c1c;
        border-left: 6px solid #a51c30; /* Harvard Crimson */
        color: #fff;
        min-width: 40%;
        border-radius: 8px;
        font-size: 2.2em;
        font-weight: bold;
        box-shadow: 0 4px 10px rgba(0,0,0,0.4);
        animation: inX-r 0.4s;
    }

    .subject {
        margin-top: 20px;
        padding: 40px 50px;
        background-color: #1c1c1c;
        color: #ddd;
        min-width: 40%;
        border-radius: 8px;
        font-size: 1.3em;
        width: 60%;
        line-height: 1.7em;
        box-shadow: 0 4px 10px rgba(0,0,0,0.4);
        animation: inX 0.4s;
        font-size: 1em;
        white-space:initial;

    }


    .delete, .date {
        font-family: inherit;
        text-decoration: none;
        font-size: 1em;
        padding: 12px 30px;
        border-radius: 32px;
        border: none;
        cursor: pointer;
    }

    .delete {
        background: #a51c30; /* Harvard Crimson */
        color: #fff;
        bottom: 30px;
        right: 30px;
    }

    .date {
        background: #1c1c1c;
        color: #ccc;
        border: 1px solid #333;
        bottom: 30px;
        left: 30px;
    }

    .delete:hover, .date:hover {
        opacity: 0.9;
        transform: scale(1.05);
    }
    .subject > p > a{
        color: rgb(0, 242, 255);
        text-decoration: none;
        transition: 0.3s;
    }
    .subject > p > a:hover{
        text-decoration: underline;
    }
    .subject h1, .subject h2 {
        color: #eee;
        margin-bottom: 10px;
    }
    .subject p {
        line-height: 1.6;
        margin-bottom: 10px;
    }

    .btn-f{
        text-decoration: none;
        max-width: 160px;
        padding: 15px 20px;
        background-color: #a51c30;
        color: white;
        border: none;
        border-radius: 20px;
        right: 5px;
        bottom: 10px;
        margin: 130px 15px 0 0 ;
        position: fixed;
        font-size: 1.2em;
        transition: 0.4s;
    }
    .btn-f:hover{
        scale: 1.1;
    }
</style>

{% if is_admin %}
    <a class="btn-f" href="{% url 'main:DWclass' lesson_id %}">Delete</a>
{% endif %}
<div class="main">
    <div class="Title-d">{{title}}</div>
    <div class="subject" style="white-space: pre-wrap;">{{ mark|safe }}</div>
</div>
{% if is_sender %}
    <a href="{% url 'main:delete_m' message.id %}" class="delete">Delete</a>
{% endif %}
<!-- <div class="date">{{message.DateTime.date}}</div> -->




 


{% endblock %}