prvard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prvard_main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prvard_main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_f, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_f, name='logout'),
    path('leave', views.leave, name='leave'),
    path('delete/<int:university_id>', views.delete, name='delete'),
    path('join', views.join, name='join'),
    path('Create_University', views.createu, name='createu'),
    path('Create/University/<str:Theme>', views.createu_f, name='createu_f'),
    path('mobile-blocked', views.mobile_blocked, name='mobile_blocked'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>', views.profile_other, name='profile_o'),
    path('members', views.members, name='members'),
    path('message', views.send_message, name='message'),
    path('inbox', views.inbox, name='inbox'),
    path('send', views.send, name='send'),
    path('message/<int:message_id>', views.show_message, name='show'),
    path('delete/message/<int:message_id>', views.delete_m, name='delete_m'),
    path('classes/', views.all_classes, name='all_classes'),
    path('entroll/<int:id>', views.Entroll, name='entroll'),
    path('Create/Class', views.createC, name='createC'),
    path('Delete/User/<int:id>', views.Delete_u, name='delete_u'),
    path('Login/<int:id>', views.Oclass, name='Oclass'),
    path('Class/<int:id>', views.Open_Class, name='Opclass'),
    path('Leave/Class/<int:id>', views.leaveC, name='Lclass'),
    path('Delete/Class/<int:id>', views.DeleteC, name='Dclass'),
    path('Member/Class/<int:id>', views.Cmember, name='Mclass'),
    path('Create/Week/<int:id>', views.Cweek, name='Cweek'),
    path('Edit/Week/<int:id>', views.Eweek, name='Eweek'),
    path('Show/Week/<int:id>', views.ShowW, name='ShowW'),
    path('Chat/Class/<int:id>', views.Chat1, name='Cclass'),
    path('Add/Message/Class/<int:id>', views.add_message, name='ACclass'),
    path('Delete/Lesson/<int:id>', views.Delete_L, name='DWclass'),


]

templates/prvard/createu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prvard</title>
    <link rel="stylesheet" href="{% static 'prvard/css/createu.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
    
</head>
<body>
    <img src="{% static 'prvard/img/prroer.png' %}" alt="" class="img" width="100">
    <div class="profile-menu">
        <a href="{% url 'main:index' %}">Home</a>
        <a href="{% url 'main:logout' %}">Logout</a>
    </div>
       <div class="content">
        <div class="prvard">Prvard</div>
        <p class="title">CHOOSE YOUR UNIVERSITY</p>
        <div class="choices">
            <a href="{% url 'main:createu_f' 'Yale' %}" class="one choice"><img src="{% static 'prvard/img/yale.png' %}" alt="" width="70px"></a>
            <a href="{% url 'main:createu_f' 'Harvard' %}" class="one choice"><img src="{% static 'prvard/img/harvard.png' %}" alt="" width="70px"></a>
            <a href="{% url 'main:createu_f' 'MIT' %}" class="two choice"><img src="{% static 'prvard/img/mit.png' %}" alt="" width="70px"></a>
        </div>
    </div>


<script>
    const profile = document.querySelector('.img');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/prvard/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prvard</title>
    <link rel="stylesheet" href="{% static 'prvard/css/style.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>

    
</head>
<body>
    <img src="{% static 'prvard/img/prroer.png' %}" alt="" class="img" width="100">
    <div class="profile-menu">
        <a href="{% url 'main:index' %}">Home</a>
        <a href="{% url 'main:logout' %}">Logout</a>
    </div>
       <div class="content">
        <div class="prvard">Prvard</div>
        <p class="title">CHOOSE YOUR UNIVERSITY</p>
        <div class="choices">
            <a href="{% url 'main:createu' %}" class="one choice">Create new university</a>
            <a href="{% url 'main:join' %}" class="two choice">Join current university</a>
        </div>
    </div>


<script>
    const profile = document.querySelector('.img');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/prvard/join.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prvard | Join University</title>
    <link rel="stylesheet" href="{% static 'prvard/css/style.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>

    
</head>
<body>
    <img src="{% static 'prvard/img/prroer.png' %}" alt="" class="img" width="100">
    <div class="profile-menu">
        <a href="{% url 'main:index' %}">Home</a>
        <a href="{% url 'main:logout' %}">Logout</a>
    </div>
    <div class="content">
        <div class="prvard">Prvard</div>
        <p class="title">Join Current University</p>
        <form action="{% url 'main:join' %}" method="post">
            {% csrf_token %}
            {% if message %}
                <div class="message">{{message}}</div>
            {% endif %}
            <input type="text" name="id" id="id" placeholder="ID">
            <input type="submit" value="Join" class="btn">
        </form>
    </div>

<script>
    const profile = document.querySelector('.img');
    const menu = document.querySelector('.profile-menu');

    profile.addEventListener('click', function (e) {
        e.stopPropagation();
        if (menu.style.display === 'block') {
        menu.style.display = 'none';
        } else {
        menu.style.display = 'block';
        }
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
</script>
</body>
</html>

templates/prvard/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prvard | Login</title>
    <link rel="stylesheet" href="{% static 'prvard/css/login.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
</head>
<body>
    <a href="{% url 'main:index' %}"><img src="{% static 'prvard/img/prroer.png' %}" alt="" class="img" width="100"></a>    <div class="content">
        <div class="card">
            <div class="title">Prvard</div>
            <form action="{% url 'main:login' %}" method="post">
                {% csrf_token %}
                <div class="sign">Sign In</div>
                <div class="message">{{message}}</div>
                <div class="label">Username</div>
                <input type="text" name="username" class="input">
                <div class="label">Password</div>
                <input type="password" name="password" class="input">
                <input type="submit" value="Sign In" class="btn">
                <a class="other" href="{% url 'main:register' %}">Register?</a>
            </form>
        </div>
    </div>
</body>
</html>

templates/prvard/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prvard | Register</title>
    <link rel="stylesheet" href="{% static 'prvard/css/register.css' %}">
    <script src="{% static 'prvard/js/main.js' %}"></script>
</head>
<body>
    <a href="{% url 'main:index' %}"><img src="{% static 'prvard/img/prroer.png' %}" alt="" class="img" width="100"></a>    <div class="content">
        <div class="card">
            <div class="title">Prvard</div>
            <form action="{% url 'main:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="sign">Register</div>
                <div class="message">{{message}}</div>

                <div class="label">Username</div>
                <input type="text" name="username" class="input">

                <div class="label">Password</div>
                <input type="password" name="password" class="input">

                <div class="label">Confirmation</div>
                <input type="password" name="confirmation" class="input">

                <div class="label">Full Name</div>
                <input type="text" name="name" class="input">

                <div class="label">Profile Photo</div>
                <input type="file" name="photo" class="input">

                <input type="submit" value="Register" class="btn">
                <a class="other" href="{% url 'main:login' %}">Sign In?</a>
            </form>
        </div>
    </div>
</body>
</html>